version: "3"

services:

  db:
    image: mdillon/postgis:9.6-alpine
    container_name: db
    ports:
      - "8432:5432"
    environment:
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: pycsw
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata

  pycsw:
    image: juozasg/pycsw-py2
    container_name: pycsw
    ports:
      - "8095:8000"
    volumes:
      - ./pycsw.cfg:/etc/pycsw/pycsw.cfg
      - ../records:/records
    entrypoint:
      - "python"
      - "/usr/local/bin/entrypoint.py"
      - "--workers"
      - "6"



volumes:
  db-data:
